language: php
sudo: false

matrix:
  include:
    - php: 7.4
    - php: nightly
      env: composerargs="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.4' ]]; then PHPUNIT_FLAGS="--coverage-clover ./clover.xml"; else PHPUNIT_FLAGS=""; fi
  - composer update --prefer-source $composerargs -n

script:
  - ./vendor/bin/psalm
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS
  - ./vendor/bin/composer-require-checker
  - if php -i |grep -qE xdebug; then ./vendor/bin/infection --log-verbosity=none --threads=4 --min-msi=100 --min-covered-msi=100; fi
  - ./vendor/bin/phpcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ -f clover.xml ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi
